```typescript
const userInfo: any = undefined;

function catchError(name: string){
    return function(target: any, key: string, descriptor: PropertyDescriptor){
        const fn = descriptor.value;
        descriptor.value = function(){
            try {
                fn();
            } catch (e) {
                console.log(`userInfo.${name}存在问题..`)
            }
        }
    }
}

class Person {

    @catchError('name')
    getName(){
        return userInfo.name;
    }

    @catchError('age')
    getAge(){
        return userInfo.age;
    }
}

const p = new Person();
p.getName();
p.getAge();
```
